default_stages: [commit]
fail_fast: false
minimum_pre_commit_version: "2.17.0"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8 # Use the sha or tag you want to point at
    hooks:
      - id: prettier

  - repo: local
    hooks:
      # See `local_pre_commit_hooks/validate_commit_message.py` for notes/details.
      - id: validate-commit-msg
        name: Validate Commit Message
        language: system
        entry: python local_pre_commit_hooks/validate_commit_message.py
        # This worked for me:
        # https://github.com/pre-commit/pre-commit/issues/1517#issuecomment-824067692
        args: [.git/COMMIT_EDITMSG]
        stages: [commit-msg]
        always_run: true
        verbose: true

# sets up .pre-commit-ci.yaml to ensure pre-commit dependencies stay up to date
ci:
  autoupdate_schedule: weekly
  skip: []
  submodules: false
